server:
  port: 9999
spring:
  redis:
    host: 192.168.11.200
    database: 0
  datasource:
    url: jdbc:mysql://localhost:3306/tadmin?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
mybatis-plus:
  mapper-locations: classpath:mappers/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
sa-token:
  token-name: token
  timeout: 2592000
  activity-timeout: -1
  is-concurrent: false
  is-share: false
  token-style: uuid
  is-log: true
