server:
  port: 9999
spring:
  redis:
    host: 192.168.11.200
    database: 0
  datasource:
    url: jdbc:mysql://localhost:3306/tadmin?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
mybatis-plus:
  mapper-locations: classpath:mappers/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# Sa-Token ??
sa-token:
  alone-redis:
    host: 192.168.11.200
    database: 1
    port: 6379
  # token?? (????cookie??)
  token-name: token
  # token??????s ??30?, -1??????
  timeout: 2592000
  # token????? (???????????token??) ??: ?
  activity-timeout: -1
  # ???????????? (?true???????, ?false?????????)
  is-concurrent: false
  # ?????????????????token (?true?????????token, ?false?????????token)
  is-share: false
  # token??
  token-style: uuid
  # ????????
  is-log: true